config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    resources :comments, only: [:index, :destroy]
    resources :users, only: [:index, :show, :edit, :update]
  end

  scope module: :public do
    root to: 'homes#top'
    resources :trip_plans, only: [:new, :create, :show, :edit, :update, :destroy]do
      collection do
        get :research
      end
      resources :trip_plan_details, only: [:new, :create, :edit, :update, :destroy]do #trip_plan_detailをネストさせている（trip_planの投稿に紐づけさせるため）
      end
      resource :likes, only: [:create, :destroy]do #likeをネストさせている（trip_planの投稿に紐づけさせるため）,resourceを単数形にすると:idが含まれなくなる
      end
      resources :comments, only: [:create, :edit, :update, :destroy]do #commentをネストさせている（trip_planの投稿に紐づけさせるため）
      end
    end

    get '/users' => 'users#index'
    get '/users/my_page' => 'users#my_page'
    get '/users/information/edit' => 'users#edit'
    patch '/users/information' => 'users#update'
    get '/users/stop' => 'users#stop'
    patch '/users/withdraw' => 'users#withdraw'

    resources :users, only: [:show]do
      member do
        get :likes
      end
    end

    resources :users, only: []do
      member do
        get :follows, :followers
      end
      resource :relationships, only: [:create, :destroy]
    end

    resources :trip_plan_details, only: [] do
      resource :reviews, only: [:create, :show, :edit, :update]do
      end
    end

  end

devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
  sessions: "admin/sessions"
}

devise_for :user, controllers: {
  registrations: "public/registrations",
  sessions: 'public/sessions'
}

#ゲストログイン機能
devise_scope :user do
  post 'users/guest_sign_in', to: 'public/sessions#guest_sign_in'
end



  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TripRecord</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header class="shadow-sm">
      <nav class="navbar navbar-expand-sm navbar-color bg-light mt-3 mb-3">
        <div class="container">
          <div class="collapse navbar-collapse" id = "navbarNavDropdown">
            <div class="navbar-brand nav-link text-danger"><%= image_pack_tag 'rogo.jpg', :size =>'80x40' %></div>
            <ul class="navbar-nav ml-auto">
              <% if user_signed_in? %>
                <li class="nav-item">
                 <%= link_to users_path, class:"nav-link text-dark" do %>
                  <i class="fas fa-history fa-2x"></i>
                 <% end %>
                <li class="nav-item">
                 <%= link_to research_trip_plans_path, class:"nav-link text-dark" do %>
                  <i class="fab fa-sistrix fa-2x"></i>
                 <% end %>
                <li class="nav-item">
                 <%= link_to new_trip_plan_path, class:"nav-link text-dark" do %>
                  <i class="fas fa-plus fa-2x"></i>
                 <% end %>
                <li class="nav-item">
                 <%= link_to users_my_page_path, class:"nav-link text-dark" do %>
                  <i class="fas fa-home fa-2x"></i>
                <% end %>
                <li class="nav-item">
                  <%= link_to destroy_user_session_path, method: :delete, class:"nav-link text-dark" do %>
                  <i class="fas fa-sign-out-alt fa-2x"></i>
                 <% end %>
                <li class="nav-item">
                  <%= link_to users_stop_path, class: "nav-link text-dark", "data-confirm" => "本当に退会しますか？" do %>
                  <i class="fas fa-user-alt-slash fa-2x"></i>
                <% end %>
                <li class="nav-item">
                  <%= link_to  likes_user_path(current_user), class: "nav-link text-dark" do %>
                  <i class="fas fa-heart fa-2x"></i>
                <% end %>

              <% elsif admin_signed_in? %>
                <li class="nav-item">
                 <%= link_to admin_users_path, class:"nav-link text-dark" do %>
                  <i class="fas fa-users fa-2x"></i>
                 <% end %>
                <li class="nav-item">
                 <%= link_to admin_comments_path, class:"nav-link text-dark" do %>
                  <i class="fas fa-comments fa-2x"></i>
                 <% end %>
                <li class="nav-item">
                 <%= link_to destroy_admin_session_path, method: :delete, class:"nav-link text-dark" do %>
                  <i class="fas fa-sign-out-alt fa-2x"></i>
                 <% end %>

              <% else %>
                <li class="nav-item">
                 <%= link_to root_path, class:"nav-link text-dark" do %>
                  <i class="fas fa-plane-departure fa-2x"></i>
                 <% end %>
              <% end %>
              </li>
            </ul>
          </div>
        </div>
      </nav>
    </header>

    <%= yield %>

  </body>
</html>